apiVersion: v1
kind: Service
metadata:
  name: argo-automation-app
  labels:
    app: argo-automation-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: argo-automation-app

