apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBNPR6kZwQ5KsniETLyPolch29mgnjZCrfuQhXAurh+tcesSrXP7uFooYrWPCGTHXkcQg6nVqjAqP6yNCOpdUZQKii7RcB2v2zYbG2pYJoLrZ5PHFxEMctGQ0GXegnXOV3ptuUoQGu/K19u3v589k4j5ueAbLF/ZWib7qb7o/RV5sUxIIjYUZ3rATVAuP0HHzkyQYjTsWpbqq37icJyUOl+DR1cR/SfsQ5Y+MbV35WmQzt2u0bEy058ufWgiG8v2PSYMx7yDkyBiybpEA3+3+/ARRwurUhcLMjM1jU8KoPbH/FijiR2QpB70/ZriDuKvpYRhYoUcLe8XXx0LkPq7h4E9BWkcX7gpSuONCDLBh6jSq9rnwBNmAAsNfXrKajChNlERkCKAVlVvL71AjFcOei1d/NZV8hLLUytspges0njhgHihAvjDp8uXGrhZjFaXiVPk/eOVrWyNTXFI4x+Chcj2XF0qnWUEvIlqrBbri1GXf6Qpv8KmKeBpU75mO+rVQAF0cRn7TppcBg7lENa3Z5Ma83a2ctRxLbggPIFsm9ViF8sf2ayb16fIlUUpjRrhbLLgOGdLzROYXVqIY/Cepafx6n/FLO/mYfOiGkuq/3GpCYygoakIrFpId0YQo9R+LlUPsOxGBylA5kBZ+ygVRBMavLwn39NGqhhipJR3BjJBILFXJNGtvcEhZ7VHsvbb5MsjxWTiayYxAKoja8hhLymfO5idcRCCmx4pZq/77leSpGqXWNAGF+T
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
