apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAwWUqLjxSr42Xg7XY/J7mSnlxBsqRuZUzM1G0vDegpzhMyAHK4jZ3f6T5VI9Evwi9MBabOjphuuYFquGMRvehCsIsnMx13tySBOdDlhsRvKnYBlz/7/27JHAxV6HQnW5uSVSe7ZI7B0g4vHVQzg0DRVxhd1a+uMG7efkifYYjk918flNI3oAtPWkVafm76IDSrYNsxXMdbysUK98TedWc3q0uKGQeXekaEdR/H4BiT6rJadFrWKHej7AAF8RC+puDOAtOV7MjkzkIQR5To3fhzUS6uo0D0thWAvBF3Ylauuww2HK6rziMcsoQ3X4rqq3GtHT4HQAhqJURBF1aw6/2dJ98Te4yEkf5urzMGxf9JIk1r+D9DC7q0CNDIWGYXL3oyAi3f2CFOYcZ4vjUNFz+K1HepEOnwbOSFJPPmFIGAHNWJCQUbxzttBM1Exyh0FKJ/s6Iirtwb7x18Vj9+SOlL3In7HJnGXWvj8Nxb05w9Bol4ii2H6itAY4cHXptFO7T/RrstBO8cQ4n+JSNufy0ovW4hV79//rpcf15Jw/2wlAaJMUcRnhXcJl3t0sHoyqmIknFGId7Sdx3B2B/ATgQMULhut+8whQrBSj2PvThE6o0kBaGWG+gvgLTDaW9nnN9q2Szz32F4E1WfPCYsoymO4pumclyiY7LxKpkZGBP0OSfX/DQxE9N6YfQHKmdhdFA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
